name: agent-health

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Ping homepage
        run: |
          curl -s -S -I https://creatorhavn.com | head -n 1
