name: orchestrate

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build-next:
    name: Build Next.js (app/nextjs)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app/nextjs/package-lock.json

      - name: Install deps
        working-directory: app/nextjs
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        working-directory: app/nextjs
        env:
          NEXT_TELEMETRY_DISABLED: 1
          # Stripe/DB-Env nur setzen, wenn vorhanden – Next liest sie ggf. zur Buildzeit
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        run: npm run build
